#botのバージョン(helpコマンド等で使用される)
bot_version="1.0.0"
#botの名前(Discordコマンドで使用される)
bot_name="mfsbot-v2"
#botのtoken(必須)
bot_token="NDI0NzU4ODY2MTY1ODkxMDcy.Xvuspw.etpMGdILzM_ExCrh5Q5OsTevmCo"
#botのコマンドにつける!playの!の部分に当たる物
bot_prefix="yx!"
#botステータス
bot_status="テスト稼働中"